// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0upSCVLtkGIUGJ8_rMvvaGsaCaFzw_rI',
    appId: '1:1008044488359:web:4886e6c3161a6aa0ea0d82',
    messagingSenderId: '1008044488359',
    projectId: 'healthcare-dbb91',
    authDomain: 'healthcare-dbb91.firebaseapp.com',
    storageBucket: 'healthcare-dbb91.firebasestorage.app',
    measurementId: 'G-PMELEENCY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1mU3I-jPJdQQbM1c_NaaZ0Ko8VDfHuZk',
    appId: '1:1008044488359:android:a5185cd2f263e42eea0d82',
    messagingSenderId: '1008044488359',
    projectId: 'healthcare-dbb91',
    storageBucket: 'healthcare-dbb91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5SZFlVAeEiNyei2f99LQvONuNJ-A5Rq8',
    appId: '1:1008044488359:ios:706a8bd6ee0decb9ea0d82',
    messagingSenderId: '1008044488359',
    projectId: 'healthcare-dbb91',
    storageBucket: 'healthcare-dbb91.firebasestorage.app',
    iosBundleId: 'com.example.healthCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5SZFlVAeEiNyei2f99LQvONuNJ-A5Rq8',
    appId: '1:1008044488359:ios:706a8bd6ee0decb9ea0d82',
    messagingSenderId: '1008044488359',
    projectId: 'healthcare-dbb91',
    storageBucket: 'healthcare-dbb91.firebasestorage.app',
    iosBundleId: 'com.example.healthCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0upSCVLtkGIUGJ8_rMvvaGsaCaFzw_rI',
    appId: '1:1008044488359:web:e713c79a0d56a728ea0d82',
    messagingSenderId: '1008044488359',
    projectId: 'healthcare-dbb91',
    authDomain: 'healthcare-dbb91.firebaseapp.com',
    storageBucket: 'healthcare-dbb91.firebasestorage.app',
    measurementId: 'G-CLP4WK2G0S',
  );

}